kind: pipeline
name: backend

steps:
- name: test
  image: node:latest
  commands:
  - npm install
  - npm run test:unit
  when:
    branch:
      - master
    event:
      - push
      - pull-request