---
kind: pipeline
type: docker
name: backend
steps:
  - name: test
  image: node:latest
  commands:
    - npm install
    - npm run test
  when:
    branch:
      - master
    event:
      - push
      - pull-request