kind: pipeline
name: backend

steps:
- name: test
  image: node:latest
  commands:
  - echo test
  - npm install
  - npm run test:unit
  when:
    branch:
    - main
    event:
    - push
    - pull-request