---

kind: pipeline
name: test

steps:
- name: test
  image: node:latest
  commands:
  - echo test
  when:
    branch:
    - main
    event:
    - push
    - pull-request
---

kind: pipeline
type: exec
name: deploy-local

# clone:
#   disable: true

trigger:
  branch:
  - main
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  environment:
    WWW_ROOT:
      from_secret: WWW_ROOT
  commands:
  - cd $${WWW_ROOT}
  - git pull

# ...