kind: pipeline
name: test

steps:
- name: test
  image: node:latest
  commands:
  - echo test
  when:
    branch:
    - main
    event:
    - push
    - pull-request

---

kind: pipeline
type: exec
name: staging

trigger:
  branch:
  - main
  event:
  - push
depends_on:
- test

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  environment:
    WWW_ROOT:
      from_secret: WWW_ROOT
  commands:
  - cd $${WWW_ROOT}
  - git pull